In [1]:
import numpy as np
import pandas as pd

x = np.eye(3)
print(x)

y = 5*x.copy()
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]


In [3]:
z = np.ones( (5,5) )
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
